/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface ERC721ReceiverInterface extends ethers.utils.Interface {
  functions: {
<<<<<<< HEAD
=======
    "c_0x63b7ff9d(bytes32)": FunctionFragment;
>>>>>>> develop
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
<<<<<<< HEAD
=======
    functionFragment: "c_0x63b7ff9d",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
>>>>>>> develop
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
<<<<<<< HEAD
=======
    functionFragment: "c_0x63b7ff9d",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
>>>>>>> develop
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ERC721Receiver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC721ReceiverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
<<<<<<< HEAD
=======
    c_0x63b7ff9d(
      c__0x63b7ff9d: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "c_0x63b7ff9d(bytes32)"(
      c__0x63b7ff9d: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

>>>>>>> develop
    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

<<<<<<< HEAD
=======
  c_0x63b7ff9d(
    c__0x63b7ff9d: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0x63b7ff9d(bytes32)"(
    c__0x63b7ff9d: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

>>>>>>> develop
  onERC721Received(
    operator: string,
    from: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "onERC721Received(address,address,uint256,bytes)"(
    operator: string,
    from: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
<<<<<<< HEAD
=======
    c_0x63b7ff9d(
      c__0x63b7ff9d: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0x63b7ff9d(bytes32)"(
      c__0x63b7ff9d: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

>>>>>>> develop
    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
<<<<<<< HEAD
=======
    c_0x63b7ff9d(
      c__0x63b7ff9d: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0x63b7ff9d(bytes32)"(
      c__0x63b7ff9d: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

>>>>>>> develop
    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
<<<<<<< HEAD
=======
    c_0x63b7ff9d(
      c__0x63b7ff9d: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0x63b7ff9d(bytes32)"(
      c__0x63b7ff9d: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

>>>>>>> develop
    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
