/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface IOrgIdDelegatesInterface extends ethers.utils.Interface {
  functions: {
    "addDelegates(bytes32,string[])": FunctionFragment;
<<<<<<< HEAD
=======
    "c_0x44655cf7(bytes32)": FunctionFragment;
>>>>>>> develop
    "getDelegates(bytes32)": FunctionFragment;
    "removeDelegates(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addDelegates",
    values: [BytesLike, string[]]
  ): string;
  encodeFunctionData(
<<<<<<< HEAD
=======
    functionFragment: "c_0x44655cf7",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
>>>>>>> develop
    functionFragment: "getDelegates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDelegates",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addDelegates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
<<<<<<< HEAD
=======
    functionFragment: "c_0x44655cf7",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
>>>>>>> develop
    functionFragment: "getDelegates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDelegates",
    data: BytesLike
  ): Result;

  events: {
    "OrgIdDelegatesAdded(bytes32,string[])": EventFragment;
    "OrgIdDelegatesRemoved(bytes32,string[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OrgIdDelegatesAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OrgIdDelegatesRemoved"): EventFragment;
}

export type OrgIdDelegatesAddedEvent = TypedEvent<
  [string, string[]],
  { orgId: string; delegates: string[] }
>;

export type OrgIdDelegatesAddedEventFilter =
  TypedEventFilter<OrgIdDelegatesAddedEvent>;

export type OrgIdDelegatesRemovedEvent = TypedEvent<
  [string, string[]],
  { orgId: string; delegates: string[] }
>;

export type OrgIdDelegatesRemovedEventFilter =
  TypedEventFilter<OrgIdDelegatesRemovedEvent>;

export interface IOrgIdDelegates extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IOrgIdDelegatesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addDelegates(
      orgId: BytesLike,
      dids: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "addDelegates(bytes32,string[])"(
      orgId: BytesLike,
      dids: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

<<<<<<< HEAD
=======
    c_0x44655cf7(
      c__0x44655cf7: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "c_0x44655cf7(bytes32)"(
      c__0x44655cf7: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

>>>>>>> develop
    getDelegates(
      orgId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]] & { dids: string[] }>;

    "getDelegates(bytes32)"(
      orgId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]] & { dids: string[] }>;

    "removeDelegates(bytes32)"(
      orgId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "removeDelegates(bytes32,string[])"(
      orgId: BytesLike,
      dids: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addDelegates(
    orgId: BytesLike,
    dids: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "addDelegates(bytes32,string[])"(
    orgId: BytesLike,
    dids: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

<<<<<<< HEAD
=======
  c_0x44655cf7(
    c__0x44655cf7: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0x44655cf7(bytes32)"(
    c__0x44655cf7: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

>>>>>>> develop
  getDelegates(orgId: BytesLike, overrides?: CallOverrides): Promise<string[]>;

  "getDelegates(bytes32)"(
    orgId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "removeDelegates(bytes32)"(
    orgId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "removeDelegates(bytes32,string[])"(
    orgId: BytesLike,
    dids: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addDelegates(
      orgId: BytesLike,
      dids: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "addDelegates(bytes32,string[])"(
      orgId: BytesLike,
      dids: string[],
      overrides?: CallOverrides
    ): Promise<void>;

<<<<<<< HEAD
=======
    c_0x44655cf7(
      c__0x44655cf7: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0x44655cf7(bytes32)"(
      c__0x44655cf7: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

>>>>>>> develop
    getDelegates(
      orgId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "getDelegates(bytes32)"(
      orgId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "removeDelegates(bytes32)"(
      orgId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeDelegates(bytes32,string[])"(
      orgId: BytesLike,
      dids: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OrgIdDelegatesAdded(bytes32,string[])"(
      orgId?: BytesLike | null,
      delegates?: null
    ): OrgIdDelegatesAddedEventFilter;
    OrgIdDelegatesAdded(
      orgId?: BytesLike | null,
      delegates?: null
    ): OrgIdDelegatesAddedEventFilter;

    "OrgIdDelegatesRemoved(bytes32,string[])"(
      orgId?: BytesLike | null,
      delegates?: null
    ): OrgIdDelegatesRemovedEventFilter;
    OrgIdDelegatesRemoved(
      orgId?: BytesLike | null,
      delegates?: null
    ): OrgIdDelegatesRemovedEventFilter;
  };

  estimateGas: {
    addDelegates(
      orgId: BytesLike,
      dids: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "addDelegates(bytes32,string[])"(
      orgId: BytesLike,
      dids: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

<<<<<<< HEAD
=======
    c_0x44655cf7(
      c__0x44655cf7: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0x44655cf7(bytes32)"(
      c__0x44655cf7: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

>>>>>>> develop
    getDelegates(
      orgId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getDelegates(bytes32)"(
      orgId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "removeDelegates(bytes32)"(
      orgId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "removeDelegates(bytes32,string[])"(
      orgId: BytesLike,
      dids: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addDelegates(
      orgId: BytesLike,
      dids: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "addDelegates(bytes32,string[])"(
      orgId: BytesLike,
      dids: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

<<<<<<< HEAD
=======
    c_0x44655cf7(
      c__0x44655cf7: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0x44655cf7(bytes32)"(
      c__0x44655cf7: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

>>>>>>> develop
    getDelegates(
      orgId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getDelegates(bytes32)"(
      orgId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "removeDelegates(bytes32)"(
      orgId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "removeDelegates(bytes32,string[])"(
      orgId: BytesLike,
      dids: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
