/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface NonERC721ReceiverInterface extends ethers.utils.Interface {
  functions: {
    "c_0xa2b921e2(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_0xa2b921e2",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "c_0xa2b921e2",
    data: BytesLike
  ): Result;

  events: {};
}

export interface NonERC721Receiver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NonERC721ReceiverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    c_0xa2b921e2(
      c__0xa2b921e2: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "c_0xa2b921e2(bytes32)"(
      c__0xa2b921e2: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  c_0xa2b921e2(
    c__0xa2b921e2: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0xa2b921e2(bytes32)"(
    c__0xa2b921e2: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    c_0xa2b921e2(
      c__0xa2b921e2: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0xa2b921e2(bytes32)"(
      c__0xa2b921e2: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    c_0xa2b921e2(
      c__0xa2b921e2: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0xa2b921e2(bytes32)"(
      c__0xa2b921e2: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    c_0xa2b921e2(
      c__0xa2b921e2: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0xa2b921e2(bytes32)"(
      c__0xa2b921e2: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
