/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { StringsSet, StringsSetInterface } from "../StringsSet";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x57f46b98",
        type: "bytes32",
      },
    ],
    name: "c_0x57f46b98",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60be610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80636f51ca31146038575b600080fd5b604e6004803603810190604a91906066565b6050565b005b50565b600081359050606081609d565b92915050565b60006020828403121560795760786098565b5b60006085848285016053565b91505092915050565b6000819050919050565b600080fd5b60a481608e565b811460ae57600080fd5b5056fea164736f6c6343000807000a";

type StringsSetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StringsSetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StringsSet__factory extends ContractFactory {
  constructor(...args: StringsSetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<StringsSet> {
    return super.deploy(overrides || {}) as Promise<StringsSet>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): StringsSet {
    return super.attach(address) as StringsSet;
  }
  connect(signer: Signer): StringsSet__factory {
    return super.connect(signer) as StringsSet__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StringsSetInterface {
    return new utils.Interface(_abi) as StringsSetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StringsSet {
    return new Contract(address, _abi, signerOrProvider) as StringsSet;
  }
}
