/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721Receiver } from "./ERC721Receiver";
export type { OrgIdUpgradeabilityTest } from "./OrgIdUpgradeabilityTest";
